name: Release datasync manager
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: "18.x"
      # - name: Installing dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build-ts
      # - name: Publishing datasync manager
      #   uses: JS-DevTools/npm-publish@v2.2.0
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
