name: Release datasync manager
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: "18.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run build-ts
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        with:
          prefix: 'v'
          fallback: v2.0.4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: print-tags
        id: print-tags
        if: ${{ '${{steps.package-version.outputs.current-version}}' != ${'${{{steps.previoustag.outputs.tag:1}}}'}}}
        run: echo '${{steps.package-version.outputs.current-version}}'
      - name: Publishing datasync manager
        if: ${{ 'v${{steps.package-version.outputs.current-version}}' != '${{steps.previoustag.outputs.tag}}'}}
        uses: JS-DevTools/npm-publish@v2.2.0
        id: npm-release
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: github-release
        id: github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ 'v${{steps.package-version.outputs.current-version}}' != '${{steps.previoustag.outputs.tag}}'}}
        run:  gh release create --verify-tag v${{ steps.package-version.outputs.current-version }} --title "Release ${{ steps.package-version.outputs.current-version }}" --generate-notes