name: Release datasync manager
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: "18.x"
      - name: Installing dependencies
        run: npm install
      - name: Build
        run: npm run build-ts
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        with:
          prefix: 'v'
          fallback: 2.0.4
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: print-tags
        id: print-tags
        run: echo "${{steps.package-version.outputs.current-version}} ${{steps.previoustag.outputs.tag}}"
      - name: Publishing datasync manager
        uses: JS-DevTools/npm-publish@v2.2.0
        with:
          token: ${{ secrets.NPM_TOKEN }}
